#import "../template.typ": *
= Introduction

Formalization of mathematical proofs refers to the process of writing machine-checkable proofs in a proof assistant such as Lean@lean4, Rocq@rocq, or Isabelle@isabelle. At first glance, this process may appear to be a straightforward translation from pen-and-paper proofs into a formal language. In practice, however, formalization is significantly more involved. It often reveals many hidden steps that are typically carried out implicitly in a mathematician’s head when reasoning informally. As a result, even seemingly trivial tasks—such as formulating correct definitions or theorem statements—can require substantial effort. More subtly, higher-level decisions, such as choosing an appropriate proof schema, often turn out to be even more demanding@anne.

This project is carried out using the proof assistant Lean and its _mathlib_ library@mathlib, choosing basics from finite group as the main target of investigation for the following reasons. Firstly, group theory is typically the initial major topic encountered by undergraduate students when learning abstract algebra. Many subsequent areas including ring theory and commutative algebra, are built upon concepts from it. Secondly, as the group theory component of mathlib is among its most mature parts, it provides a suitable foundation for formalization. Meanwhile, group theory serves a foundational role both in mathematics and within the structure of mathlib, meaning that its corresponding APIs are designed to be highly abstract and broadly applicable. 

As a consequence, the formalization of group-theoretic theorems using mathlib often requires particularly careful treatment. Fewer specialized automation tools are available at this level, and successful formalizations frequently depend on choosing proof strategies that align closely with the existing API structure. Otherwise, one might need significant manual efforts to bridge mismatches between proof constructions operating at unsuitable level of abstraction.

Following the narrative of Chapter 3, Quotient Groups and Homomorphisms, from _Abstract Algebra_ by Dummit and Foote@Dummit, this project formalizes two selected exercises. The first concerns _abelian simple groups_, and the second concerns _Hall subgroups_. These examples are chosen to concretely illustrate how textbook proofs interact with existing formal APIs in section 3.3 and section 4.3, how implicit assumptions must be made explicit in section 3.2 and 4.2, and how proof strategies may need to be adapted in the formal setting in section 4.3. In addition, the project includes a case study of contributing a pull request to mathlib in section 3,4 and reflects on the role that proof assistants can play in the learning and formalization of undergraduate mathematics in section 5.1 and 5.2.



