#import "../template.typ": *
= Introduction
 At first sight, formalizing a mathematical proof in a theorem prover such as Lean@lean4, Rocq@rocq, or Isabelle@isabelle may appear to be a straightforward translation from pen-and-paper proofs into a formal language. In practice, however, formalization is far more involved. As illustrated by large-scale projects such as the formal proof of Feit-Thompson Odd Order Theorem@feit-thompson in Rocq, formalization often exposes many intermediate steps that are carried out implicitly in informal mathematical reasoning. Tasks that appear trivial in textbook presentations—such as formulating precise definitions or stating a theorem correctly—can require substantial effort in a formal setting. Even more demanding are higher-level design decisions, for instance the choice of an appropriate proof schema or the organization of algebraic structures.

This project is carried out using the proof assistant Lean and its Mathlib library@mathlib, with basic topics from finite group theory serving as the main focus for the following reasons. Firstly, group theory is typically the initial major topic encountered by undergraduate students when learning abstract algebra. Many subsequent areas including ring theory and commutative algebra, are built upon its concepts. Secondly, as the group theory component in Mathlib is well-developed @mathlib_paper, it provides a suitable foundation for formalization. 

The corresponding group-theoretic APIs in Mathlib are designed to be highly abstract and broadly applicable. Consequently, formalization within this setting requires particular care. Successful developments typically rely on proof strategies that align closely with the existing abstraction layers. When reasoning is carried out at an incompatible level of abstraction, substantial additional effort may be required to reconcile the resulting structural mismatches.

Following the narrative of Chapter 3, Quotient Groups and Homomorphisms, from _Abstract Algebra_ by Dummit and Foote@Dummit, this project formalizes two selected exercises. The first concerns _abelian simple groups_, and the second concerns _Hall subgroups_. These examples are chosen to concretely illustrate how textbook proofs interact with existing formal APIs in section 3.3 and section 4.3, how implicit assumptions must be made explicit in section 3.2 and 4.2, and how proof strategies may need to be adapted in the formal setting in section 4.3. In addition, the project includes a case study of contributing a pull request to mathlib in section 3,4 and reflects on the role that proof assistants can play in the learning and formalization of undergraduate mathematics in section 5.1 and 5.2.



