= Introduction (2 pages)

In recent years, the formalization of mathematical proofs has become an increasingly important topic in both mathematics and computer science (*citation*).
(*Examples to be added.*) It refers to the process of writing machine-checkable proofs in a proof assistant such as Lean, Rocq, or Isabelle (*citation*). At first glance, this process may appear to be a straightforward translation from pen-and-paper proofs into a formal language. In practice, however, formalization is significantly more involved. It often reveals many hidden steps that are typically carried out implicitly in a mathematician’s head when reasoning informally (*citation*). As a result, even seemingly trivial tasks—such as formulating correct definitions or theorem statements—can require substantial effort (*citation*). More subtly, higher-level decisions, such as choosing an appropriate proof schema, often turn out to be even more demanding (*citation*).

This project is carried out using the proof assistant Lean and its mathlib library (*citation*). Group theory, which studies algebraic structures encoding symmetry, is chosen as the main target of investigation in this project for the following reasons. It is typically the first major topic encountered by undergraduate students when learning abstract algebra. Many subsequent areas including ring theory and commutative algebra, are built upon concepts from group theory. As the group theory component of mathlib is among its most mature parts, it provides a suitable foundation for formalization. At the same time, the foundational role of group theory, both in mathematics and within the structure of mathlib, means that its corresponding APIs are designed to be highly abstract and broadly applicable. 
As a consequence, the formalization of group-theoretic theorems using mathlib often requires particularly careful treatment. Fewer specialized automation tools are available at this level, and successful formalization frequently depend on choosing proof strategies that align closely with the existing API structure. Otherwise, significant manual effort is needed to bridge mismatches between proof constructions operating at different level of abstraction.


Several interesting observations arise during the process of formalizing group-theoretic theorems on top of mathlib: in some cases, the structure of formal proofs closely aligns with standard pen-and-paper arguments found in the literature; in other cases, however, formalization exposes a tension between informal proofs and their formal counterparts. Moreover, many assumptions that remain implicit in informal reasoning must be made explicit in the formal setting, and the act of formalization itself reshapes one’s understanding of the underlying mathematical content.

Following the narrative of Chapter 3, Quotient Groups and Homomorphisms, from Abstract Algebra by Dummit and Foote (*citation*), this project formalizes two selected exercises. The first concerns _abelian simple groups_, and the second concerns _Hall Subgroups_. These examples are chosen to concretely illustrate how textbook proofs interact with existing formal APIs, how implicit assumptions must be made explicit, and how proof strategies may need to be adapted in the formal setting. In addition, the project includes a case study of contributing a pull request to mathlib and reflects on the role that proof assistants can play in the learning and formalization of undergraduate mathematics.



