#import "../template.typ": *

= Background

This section presents the necessary mathematical and technical background for the subsequent formalization, including essential notions from group theory, key mechanisms of Lean, and an overview of the Mathlib environment.

== Group Theory
We recall some basic definitions from group theory.

A _group_ is a set $G$ together with a binary operation
$dot.op : G times G arrow.r G$ satisfying the following axioms: associativity for all $g in G$, $(g_1 dot g_2) dot g_3 = g_1 dot (g_2 dot g_3)$; the existence of a neutral element $e_G$; the existence of an inverse element $g^(-1)$. If all elements of a group also satisfy commutativity, then it is called _abelian group_ or _commutative group_. The _cardlinality_ of a group $G$, denoted as $|G|$, is defined as the cardinality of its underlying set. A group is finite if $|G| < infinity$, and infinite otherwise. The _order of an element_ $g in G$ is the smallest positive integer $n$ such that $g^n = e_G$, it is infinite if no such integer exist. 

A _group homomorphism_ is a function between groups $f : G arrow.r H$ that preserves the group operation: for all $x,y in G$, $f(x dot y) = f(x) dot_H f(y)$. A homomorphism $g$ is called a left inverse of $f$ if
$g compose f = id_G$, and a right inverse if
$f compose g = id_H$, where $id_G$ and $id_H$ denote the identity maps
on $G$ and $H$, respectively. The _kernel_ of a homomorphism, is defined as $ker(f) = {g in G| f(g) = e_H}$. An _isomorphism_ is a homomorphism with a left and a right inverse. When two groups are _isomorphic_, denoted as $G_1 tilde.equiv G_2,$ they have the same group theoretic structure. 

There are two ways to obtain "smaller groups" from a given group: by forming a "smaller" _subgroup_, or by forming a _quotient group_. 

A _subgroup_ is a subset $H$ of $G$ whose elements also satisfy the three axioms above. Subgroup relation is noted as $H lt.eq G$ in this thesis. An important class of subgroups consists of cyclic subgroups, that is, subgroups generated by a single element. Among all subgroups of a group $G$, there is always a smallest one, namely the trivial subgroup ${e}$, and a largest one, namely $G$ itself. These form the bottom and top elements of the lattice of subgroups of $G$. A group is called _simple_ if it has no non-trivial _normal subgroups_. Subgroup $H$ is a normal subgroup of $G$ if and only if $g dot H dot g^(-1) = H$ for all $g in G$.

The _quotient_ of a group by a subgroup is defined via an equivalence relation. Let $G$ be a group and let $H$ be a subgroup of $G$, we define an equivalence relation on $G$ by $ g ~ h <==> g^(-1) dot h in H. $ The equivalence class of an element $g in G$ is given by $[g] = g dot H$, which is called the _left coset_ of $H$ in $G$. The set of left cosets forms a partition of a group, which means any two distinct left cosets are disjoint, and the union of all left cosets is exactly the group itself. The _index_ of $H$ in $G$, denoted as $[G:H]$, is defined as the cardinality of left cosets of $H$ in $G$, equivalently: $[G:H] = |G \/H|$. The set of left cosets, denoted as $G \/ H$, is called the quotient of $G$ by $H$. If $H$ is a normal subgroup of $G$, it admits a quotient group construction. In this case, $G \/ H$ is called a _quotient group_ of $G$ by $H$.

The following definition and theorems provide the main algebraic tools for the proofs in this project. For more details, readers could check this book@Dummit.

#definition[Hall subgroup][A subgroup $H$ is called a Hall subgroup of a finite group $G$, if its index is coprime to its cardinality.]

Lagrange's theorem relates the order of a subgroup to the order of its ambient group via the notion of index.
#theorem[Lagrange's theorem][Let $G$ be a finite group and $H$ is a subgroup of $G$. Then $|G : H| = |G| \/ |H|.$]
The first isomorphism theorem states that every group homomorphism induces an isomorphism between the quotient of the domain by its kernel and its image. 
#theorem[The first isomorphism theorem][If $phi:$ $G arrow H$ is a group homomorphism, then $ker(phi)$ is a normal subgroup of $G$, and $G \/ker(phi) tilde.equiv phi(G).$]
The second isomorphism theorem describes the interaction between inclusion and intersection of subgroups in terms of quotient groups.
#theorem[The second isomorphism theorem][Let $G$ be a group and let $A, B$ be subgroups of $G$ such that $a dot B dot a^(-1) = B $ for all $a in A$. Under this assumption, we have:
  - $A union.sq B$ is a subgroup of $G$
  - $B$ is a normal subgroup of $A union.sq B$
  - $A union.sq B \/B tilde.equiv A \/ (A inter.sq B)$]


== Lean
Lean@lean4 is an interactive proof assistant based on _dependent type theory_. It implements the _Curry-Howard correspondence_,  in which propositions are represented as types, and proofs correspondent to terms inhabiting these types@love. This view allows treating mathematical statements and proofs as structured objects that can be manipulated and checked by the system. To keep logical coherence, types in Lean form an infinite hierarchy of universes, identified by levels. Propositions inhabit `Prop`, which is defined as `Sort 0`. Types of universe level `u` inhabit `Type u`, which is definitionally equal to `Sort (u + 1)`. When leaving `u` implicit, it is written as `Type*`. For more information about Lean's type system, readers can consult the Lean language reference@lean4_ref.

In Lean, a mathematical theorem is introduced by keywords such as `theorem` or `lemma`, followed by a name, a list of parameters, and type annotations of this theorem@Avigad2018. A proof is then provided by constructing a term of this type. Correctness is therefore reduced to type checking. 

As an illustration, we can formulate Lagrange's theorem in Lean as follows:
```lean
theorem lagrange {G : Type*} [Group G] [Fintype G] (H : Subgroup G) :
    Fintype.card G /  Fintype.card H = 
    Fintype.card (a • H : Set G) := by sorry
```
In the example above, the name of this theorem is `lagrange`. The expression between the name and colon specify the parameters and assumptions, and the type of this theorem is expressed between the colon and colon equals. Then the colon equals introduces the proof, and the code following it constitutes the corresponding proof term. When the keyword `by` is used, the proof is written in tactic mode@Avigad2018. Tactics are tools that facilitate the construction of proof terms. When a tactic is applied, we can observe in the `Info-View` of our editor that the proof state has been modified.

In Lean, parameters enclosed in parentheses denote explicit arguments, such as `(H : Subgroup G)`, which must be provided by the user when invoking a definition or theorem. In contrast, parameters enclosed in curly braces, such as `{G : Type*}`, denote implicit arguments, meaning that Lean attempts to infer them from the context. Square brackets indicate _type class_ parameters, for instance `[Group G]`, which trigger Lean’s instance inference mechanism.

Type classes make a bundle of overloaded operations together with their types to achieve _ad-hoc polymorphism_@wadler, which means the overloaded operations may have different implementations for different types@lean4_ref. In this thesis, they are primarily used to represent algebraic structures together with the axioms they satisfy. In the example above, when the implicit type class parameters `[Group G]` and `[Fintype G]` are declared, it indicates that the type `G` is equipped with a finite group structure. Lean then attempts to synthesize a suitable instance from the environment. Once such an instance is found, all associated operations, inherited structure, and available lemmas become accessible for `G`, without requiring them to be restated explicitly.

Another important mechanism named _coercion_, which allows a term of one type to be automatically interpreted as a term of another type via a registered map, whenever the surrounding context expects the target type@lean4_ref. For instance from `Nat` to `Int`, here Lean automatically inserts the canonical embedding `Nat → Int`:

```lean example (n : Nat) : Int := n``` 

Coercions are also heavily used in algebraic structures. Sometimes we need to to it manually, like in the example above: 

```lean (a • H : Set G)```,
where the subgroup `H : Subgroup G` is explicitly coerced to its underlying set `H : Set G`.


== Mathlib 
Mathlib is currently one of the largest formal mathematics libraries, covering a wide range of mathematical topics@undergrad_math. It is organized in a highly structured and systematic way, rather than being merely a large collection of formalized theorems@mathlib_paper. Many mathematical results are formulated in library as small composable lemmas that serve as bridges, allowing more complex constructions to be built modularly through type class inference@use-and-abuse. This design becomes particularly visible how algebraic hierarchy is expressed in Mathlib, where algebraic structures are not defined independently, but through several layers by using type classes. A representative example is the Mathlib definition of a group:
```lean
class Group (G : Type u) extends DivInvMonoid G where
  protected inv_mul_cancel : ∀ a : G, a⁻¹ * a = 1
```
The keyword `extends` declares that every instance of `Group G` is at the same time an instance of `DivInvMonoid G` with an extra axiom `inv_mul_cancel`. Consequently, whenever `[Group G]` is available, Lean can also use it as an instance of `DivInvMonoid G` via type class inference. `DivInvMonoid` is defined as: 
```lean
class DivInvMonoid (G : Type u) extends Monoid G, Inv G, Div G where
  protected div := DivInvMonoid.div'
  protected div_eq_mul_inv : ∀ a b : G, a / b = a * b⁻¹ := by intros; rfl
  protected zpow : ℤ → G → G := zpowRec npowRec
  protected zpow_succ' (n : ℕ) (a : G) : zpow n.succ a = zpow n a * a := by
    intros; rfl
  protected zpow_neg' (n : ℕ) (a : G) : zpow (Int.negSucc n) a = 
    (zpow n.succ a)⁻¹ := by intros; rfl
```
The declaration above shows that `DivInvMonoid G` extends three type classes:
  - `Monoid G`, providing multiplication, the identity element, and the corresponding axioms;
  - `Inv G`, providing the operation `inv : G → G`
  - `Div G`, providing the operation `div : G → G → G`
Thus, an instance of `DivInvMonoid G` contains, as part of its data, instances of all three structures. In particular, the definition in axiom `div_eq_mul_inv`:  
`a / b = a * b⁻¹`
shows that division is implemented as multiplication by the inverse. This example shows that new operations can defined by reusing existing ones within the hierarchy.

The development of Mathlib is a collaborative, community-driven process involving contributors from around the world. Contributions are submitted via pull request and undergo rigorous code view by maintainers and viewers@baanen2025. To ensure the quality of code, a pull request often goes through several rounds of refinements, generalizations and modifications before being merged. Consequently, formalization in Mathlib is not only a mathematical formalization activity, but also an interaction with an evolving infrastructural system.

Due to the scale and complexity of the library, efficient navigation becomes an important skill in this project. Locating lemmas is crucial to avoid duplication and to reuse established results. The Mathlib documentation@doc_mathlib usually serves as my primary entry point. It is organized into thematic categories such as `GroupTheory`, `FieldTheory`, each containing several more specialized subtopics. For instance, `Coset`, `Subgroup`, `QuotientGroup` are subtopics under `GroupTheory`. Furthermore, under each subtopic, definitions are collected into  `Defs`, basic theories are placed into `Basic`, and the core results are into other labels. Using the Mathlib documentation to locate a lemma usually requires knowing the name of the lemma. Some lemmas follow naming patterns like `add_succ` and `succ_add`, while during this formalization process, the name of a lemma is not always be obvious. Tools such as _LeanSearch_ @lean_search allows us to find lemmas without full knowledge of their names,, while interatcive tactics such as `apply?` can give us hints like a partial proof. Although many commonly used results are already available in Mathlib, the development of a formal proof frequently requires introducing auxiliary lemmas tailored to the specific context.



