#import "../template.typ": *

= Background (4 Pages)

I give the necessary prelimiaries to understand the main part of this thesis in this section.

== Group Theory (1.5 Pages)
We recall some basic definitions from group theory.

A *_group_* is a set $G$ together with a binary operation
$dot.op : G times G arrow.r G$ satisfying the following axioms: associativity, the existence of a neutral element and the existence of an inverse elememt. While a *_subgroup_* is a subset $H$ of $G$ whose elements also satisfies the three axioms above. If all elements of a group also satisfies commutativity, then it is called *_Abelian group_* or *commutative group*.

An important class of subgroups is given by cyclic subgroups.
A group is called *_cyclic_* if it is generated by a single element. Among all subgroups of a group $G$, there is always a smallest one,
namely the trivial subgroup ${e}$, and a largest one, namely $G$
itself. These form the bottom and top elements of the lattice of
subgroups of $G$. A group is called *_simple_* if it has no non-trivial normal subgroups,
Simple groups can be regarded as the building blocks of group theory.

From here we adopt some standard notations and state the required
definitions more formally.

#definition[Group Homomorphism][To be filed]
#definition[Quotient Group][To be filled]
#definition[Coset][To be filled]
#definition[Normal subgroup][To be filled]
#definition[Cardinality][To be filled]
#definition[Index][To be filled]
The following key definitions are used in the theorem of this project.
#definition[Abelian Simple Group][To be filled]
#definition[Hall Subgroup][To be filled]
The following three theorems are the main tools for proving the key theorems in this project.
#theorem[Lagrange's theorem][To be filled]
#theorem[The first Isomorphism theorem][To be filled]
#theorem[The second Isomorphism theorem][To be filled]
-- and show the lattice structure here

== Lean (1 Page)
Here I introduce the necessary stuffs relating to read lean code.

What is Lean?

Why can we write mathematical proofs in Lean?
- propositions as types,
- proofs as terms, curry-howard correspondence
I could list a theorem to illustrate

How does a group theory theorem looks like and a proof approximately looks like in Lean?
eg. - keywords like : lemma, theorem, sorry
    - type annotaion
    - parameters
    - theorem statement

== Mathlib (1.5 Pages)
explain the following stuffs: 
=== The definition hierachy of group in mathlib
- *explain* Group definition hierachy in mathlib:
In mathlib the most basic definition of a group are:
```lean
class Group (G : Type u) extends DivInvMonoid G : Type u
class AddGroup (A : Type u) extends SubNegMonoid A : Type u
```

In this thesis we are mostly handling on the following extensions of basic groups, one is commutative group, the other is quotient group.

=== Distinction between group and additive group in mathlib
- *explain* the distinction and the to_additive notation in mathlib group section, and when it matter during the formalization.

=== Commutative group
- explain its usage shortly
```lean
-- An additive commutative group is an additive group with commutative (+)
class AddCommGroup (G : Type u) extends AddGroup G, AddCommMonoid G : Type u

-- A commutative group is a group with commutative (*).
class CommGroup (G : Type u) extends Group G, CommMonoid G : Type u
```

=== Normal Subgroup
- explain its usage shortly
- using N.normal as typeclass parameter
```Lean
class Subgroup.Normal {G : Type u_1} [Group G] (H : Subgroup G) : Prop
```
=== Quotient group
- explain why it is an instance
- prepare the context of its usage in latter formalization
```lean
instance QuotientGroup.Quotient.group {G : Type u_1} [Group G] (N : Subgroup G) [nN : N.Normal] : Group (G ⧸ N)
```