#import "../template.typ": *
= Formalization of a Theorem on Abelian Simple Groups(6.5 Pages)
This section documents the formalization of a theorem on abelian simple groups. A substantial part of this development has been incorporated into mathlib through an accepted pull request (*citation*). To illustrate the formalization process, we refer to the initial version of the development rather than the final merged code, as it more clearly reflects the design decisions and intermediate steps discussed in Section 3.2. However, the main idea of this section is not to explain the formalization detail, but to show how this formal proof structurally aligns with the paper proof. The section 3.4 about mathlib pull request is not a part which stands alone from the formalization of abelian simple group, but we regard it as contiuation and refinement.

== Mathematical statement
#theorem[Abelian simple Groups][Let $G$ be an Abelian simple group. Then $G tilde.equiv ZZ_p$ for some prime $p$.]
No finiteness assumption for $G$ is required. 

The rough proof idea for this theorem is as follows: every subgroup is normal in an abelian group. In an simple group, it only has trival subgroup and itself. Let $g in G$ be an non-identity element. The subgroup generated by $g$ must therefore coinside with $G$, so $G$ is cyclic. A cyclic simple group must have prime order, since every cyclic group of order $n$ has a subgroup of order $d$ for each divisor $d | n$(according to Lagrange’s theorem), a cyclic group with composite order admits a nontrivial proper subgroup. Hence, simplicity forces the order of $G$ to be prime. Since $G$ is cyclic of prime order $p$, it is isomorphic to the cyclic group $ZZ_p$. This yields the conclusion.
== API landscape

Before formalizing the theorem in Lean, it is necessary to determine an appropriate formal statement by research the relevant group theoretic API.

Firstly, we consider how to do the correct theorem statemet. In mathlib, ablelian groups are represented by typeclass `[CommGroup G]`, and simplicity is expressed as `[IsSimpleGroup G]`. *TODO: add the meaning of top and bottom.*

Expressing the statement in Lean requires more care than in the classical paper-and-pencil setting. On paper, one simply write $G tilde.equiv H$ without specifying whether the group is considered additively or multiplicatively. In contrast, mathlib distinguishes explicitly between multiplicative and additive algebraic structures, as these correspond to different typeclasses and operations. To avoid duplicating lemmas for both versions, mathlib primarily develops group theory in the multiplicative setting. Additive analogues are typically generated using the `[to_additive]` attribute. Consequently, when stating the theorem formally, one must explicitly decide whether to work in the multiplicative version or as additive. In our development, given that $ZZ_p$ is an additive group, we need an additive isomorphism as well. So the `Additive` wrapper must be employeed to the multipilicative group `G`.

Additionally, we always need to consider type correctness when working in a dependent-type based proof assistant. In Lean, a theorem must be of type `Prop`. It means that we cannot simply write down the isomorphic structure as it is in paper, since `(Additive G ≃+ ZMod p)` is a data-carrying type (of additive equivalences) rather than a proposition. Here we need the help of `Nonempty`, which is a Prop-valued type class asserting that the type `α` is inhabited. It helps to fit the isomorphism into the existential statement.

Secondly, we investigate whether there're existing tools in the library. We noticed that there's already a lemma telling the isomorphism from $ZZ_n$ to any cyclic additive group which has cardinality `n`. That solves the second half of the proof. Then we find that there's another theorem in API telling that a finite abelian simple group has prime cardinality. Since an abelian simple group must be cyclic, if we could derive finiteness only from the premises of a group is abelian and simple, then we could formalize theorem 3.1.1 in Lean and generalize the lemma in mathlib as well. Therefore, the main difficulty of this formalization reduces to deriving finiteness from the assumptions of commutativity and simplicity.

== Formalization
The theorem 3.1.1 is thus expressed in Lean as:
```lean
/-- A commutative simple group is isomorphic to `ZMod p` from some prime `p`. -/
theorem CommSimple_iso_ZMod_p [CommGroup G] [IsSimpleGroup G] :
    ∃ p : ℕ , (Nat.Prime p) ∧ Nonempty (Additive G ≃+ ZMod p) := by
  obtain ⟨g, hg⟩ := isCyclic_iff_exists_zpowers_eq_top.mp (inferInstance : IsCyclic G)
  use orderOf g; rw [← (orderOf_eq_card_of_zpowers_eq_top hg).symm]
  constructor
  · exact IsSimpleGroup.prime_card
  · exact ⟨(zmodAddCyclicAddEquiv (G := Additive G) inferInstance).symm⟩
```
Thanks to the typeclass design, we could directly get a cyclic group `hg` and its generator `g` by instance inference. They are been used as the working horse in this proof, because we want to show that `hg` is a finite cyclic group and the order of`g` must be a prime number. The tactic `constructor` splits the AND-connector, divides the theorem into two goals. In the second goal we use the lemma `zmodAddCyclicAddEquiv` from the API and solve the isomorphism for free. In the first goal, the lemma `IsSimpleGroup.prime_card` requires a `Finite α` instance. Since no such instance is available by typeclass inference, we prove finiteness of any abelian simple group separately:
```lean
/-- A commutative simple group is a finite group. -/
theorem comm_simple_is_finite : Finite α := by sorry
```
As mentioned above, we need to construct a proof term which has type `Finite α`.   Similarily, we would like to get a cyclic group by typeclass inference, not because of the nice mathematical property of cyclic group, but also because of the rich cyclic group and subgroup API. The proof idea could be that a subgroup of an infinite cyclic group is neither itself nor  trival subgroup, then the proof could be done by contradiction.

The formal proof skeleton is sketched as follows：
```lean
theorem comm_simple_is_finite : Finite α := by
  obtain ⟨g, hg⟩ :=
    (isCyclic_iff_exists_zpowers_eq_top : IsCyclic α  ↔ _).mp 
    (by infer_instance)
  by_contra hnf
  have horder : orderOf g = 0 := by sorry
  let H : Subgroup α  := Subgroup.zpowers (g ^ 2)
  have Hnorm : H.Normal := by exact Subgroup.normal_of_comm H
  have hneq_top : H ≠ ⊤ := by sorry
  have hneq_bot : H ≠ ⊥ := by sorry
  have := IsSimpleGroup.eq_bot_or_eq_top_of_normal (H := H) Hnorm
  rcases this <;> contradiction
``` 

We firstly obtain a generator `g` using typelcass inference. 
```lean
obtain ⟨g, hg⟩ :=
    (isCyclic_iff_exists_zpowers_eq_top : IsCyclic α  ↔ _).mp 
    (by infer_instance)
```
This gives a cyclic structure on `α`, with `g` generating the whole group.
To construct a term of type `Finite α`, we proceed by concradiction:
```lean 
by_contra hnf
```
In mathlib, the infinite order of an element is designed as zero. Now assuming the infiniteness, we derive that the order of the generator is zero: ```lean 
have horder : orderOf g = 0 := by sorry
```
We then define the subgroup generated by $g^2$:
```lean
let H : Subgroup α := Subgroup.zpowers (g ^ 2)

```
Since the group is commutative, every subgroup is normal, which allows us to apply the simplicity condition: 
```lean
have Hnorm : H.Normal := by exact Subgroup.normal_of_comm H
```
It remains to show that `H` is neither trivial nor the whole group. This contradicts the fact that a simple group admits only `⊥` and `⊤` as normal subgroups, completing the proof. The structure of the proof mirrors the mathematical argument, but the explicit construction of subgroups and normality witnesses makes the contradiction step fully transparent in the formal setting.

In the formalization of abelian simple groups, several aspects require explicit attention. These points do not change the underlying mathematical strategy, but illustrate how implicit reasoning in paper proofs becomes explicit in the formal setting:
- *Typeclass inference and reuse*: the proof relies heavily on Lean’s typeclass mechanism, which enables structural properties to propagate automatically throughout the development. Cyclicity is obtained via instance inference, allowing us to extract a generator without explicit construction. Likewise, normality in the abelian setting is available as an instance and can be invoked directly. This mechanism significantly reduces boilerplate and makes existing API results immediately reusable.
- *Explicit structural witnesses*:
  several steps that are immediate in the informal proof require explicit witnesses in formal proof. For instance, although every subgroup of an abelian group is normal, a term of normal subgroup  must be showed in order to feed it into related lemmas. Similarly, the subgroup $⟨g²⟩$ must be shown explicitly to be nontrivial and distinct from the whole group, corresponding to separate proof goals.
- *Type correctness*: while informal proofs rarely make type considerations explicit, in Lean type correctness is a foundational requirement, and every statement must be formulated with precise attention to the types involved.

Although the formal development may appear more technical, the overall structure of the proof remains very close to the classical pen-and-paper proof. This is mainly due to the well-designed group theory API, where concepts like cyclic groups, normal subgroups, cardinality, and simplicity are already abstracted in a way that mirrors standard mathematical practice. As a result, the formal proof does not require a fundamentally different strategy, but reveals implicities in informal math proofs into explicit terms, such as normality witnesses, typeclass instances, and data-carrying equivalences. The differences therefore lie not in the mathematical content, but in the explicit management of structure required by the dependent type theory underlying Lean.

== Mathlib pull request

Code written for a local development often prioritizes convenience or for its own project use, while library code must prioritize generality and composability and align with its design philosophy. When preparaing the PR, we usually need to do the following: changing the naming convention close to mathlib style(*citation*), improving the proof to a more compact way, breaking a huge proof into several briding lemmas. What more important are, determine the PR scope and the right location to place the contribution by throughly studying the related mathlib section, because it is required clearly in the contribution guidelines that contributors are expected to give in this information in their PR message(*citation*). 

The target theorem with unnecessary `[Finite G]` premise is `IsSimpleGroup.prime_card` which is in the file `Mathlib\GroupTheory\SpecificGeoup\Cyclic`(*citation*). Our PR is aimed to remove this premise by adding the proof of finiteness. After researching the file, we noticed that the isomorphism theorem is also not included in mathlib. Considering it serves a very classical and fundamental result in undergraduate abstract algebra, we also decide to include this isomorphism lemma in our PR. The file `Cyclic` is arranged by different namespaces with different conditions. We find that the right place to put our lemma should be namespace `IsSimpleGroup`, where we renamed the section `CommGroup` into `CommSimpleGroup` to better serve the assumptions. And the right place for the isomorphism lemma is in section `Zmod`. 

Moreover, we refactor the finiteness proof by adding a lemma which we think might be useful in other proofs since it serves as a standard fact. In our proof this lemma  is used in the proof where $<g^2> eq.not ⊥ $.  
```lean
lemma not_mem_zpowers_sq_of_orderOf_zero {g : α} (horder : orderOf g = 0) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry
```
Since it doesn't talks about abelian simple groups anymore, rather focusing on the order of elements from a group, we put this lemma in the file `Mathlib\GroupTheory\OrderOfElement`. We decide to pack this lemma togehter in one PR, because it is derived directly from the proof of finitess and stay close with the main idea of this PR. After pushing the pull request, the PR is been labeled as `t-group-theory`. Since this is our first PR, it is also been added as `new contributor`. In the PR waitlist, PRs from frequent mathlib contributor and new contributor are divided into two groups. 

Given that mathlib is a community-driven project, the communication with the mathlib maintainers/viewers and the broad mathlib community is also crucial. After having done all the preparation, we have written a nice message in mathlib channel on zulip, introducing our motivation and this PR. This action has got positive feedback -  mathlib maintainer has given us the first view very soon, even if there're still lots of PRs in the long waitlist.

The feedback received during the review process can be categorized into the following aspects: 
- *Formatting*: several remarks pointed out inconsistencies in indentation, the use of blank lines, and spacing. Although these issues do not affect correctness, they are essential for readability and for maintaining stylistic consistency within a large collaborative project such as mathlib. Before submitting the pull request, We have already reviewed the code according to these conventions; however, the feedback reveals that we have still overlooked certain details. This experience underscores how subtle and demanding stylistic consistency can be in practice.
- *Naming conventions and comments*: theorems in mathlib also have naming conventions. It must be simplist and as self explained as possible. However for a new comer it is often confusing to guess what kind of name a theorem should have. This is on the other side a very crucial skill because a better name gussing is meanwhile more efficient navigating in mathlib documentation and theorem finding. Our summarization for naming is that it tend to be a compact theorem statement which contains the information in the context than just stating the facts, there's some stuble differences in it: for example, name of theorem `comm_simple_is_finite` is suggested to change into `IsSimpleGroup.finite`, becuase it is in the namespace of `IsSimpleGroup`, and `comm` and `simple` already serve as premises. Another example is the isomorphic theorem `CommSimple_iso_ZMod_p` is suggested as `exists_prime_addEquiv_ZMod`, since it tells the existential fact of a prime number and the isomorphism is an additive equivalence. 
- *Code style*: tactic usage is compacter in mathlib, for example when it comes to the last step, if a term could directly close the goal, then there's no need to use `by refine...`. Expressions should be written in their most direct form. For example, writing `(…).symm` instead of `Eq.symm (…)` leads to more concise and conventional code.
- *Design decisions and library integration*: an interesting discussion arouses during the viewing process is whether the finitess proof should be an instance/scoped instance or just a theorem, as `Finite α` is a type class, term of this type should be registered as instance when possible. After trying to register it as an instance, we have noticed that it makes the performace of the automation tool `aesop` degenerates, and has caused a proof cannot compile anymore in a number theory file in mathlib. This is because `Finite α` is a fundamental typeclass which supports many other typeclasses. The search of automation tool is rather brutal force. Whenever a finiteness proof is needed, the instance search will be triggered. As a newly added instance with relatively narrow usage, `IsSimple.finite` has higher priority, which makes `aesop` stuck in the reasoning, causes time out. After discussing with the comminity, `scoped instance` is also not preferred because finiteness is not something that people would like to automatically get from when mentioning "abelian" and "simple". In the end, this proof is finally registed as a theorem in mathlib.
- *Lemma generalization and abstraction level*: The most exciting, and perhaps also the most frustrating, part of the review process is when the reviewer suggests generalizing a lemma. It is exciting because it provides a valuable opportunity to learn how experienced contributors think about abstraction and how a lemma can better serve the library in the long term. At the same time, it can be frustrating from the contributor’s perspective, as such suggestions often require additional work, and the connection between the proposed generalization and the original direction of the PR is not always immediately clear. The lemma that our extracted from the proof of finiteness has been asked for generalization two times:
```lean
/-The original version-/
@[to_additive]
lemma not_mem_zpowers_sq_of_orderOf_zero {g : α} (horder : orderOf g = 0) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry

/-The first generalization-/
@[to_additive]
theorem not_mem_zpowers {g : α} {k : ℕ} (horder : orderOf g = 0)
    (hk : 1 < k) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry

/-The second generalization-/
@[to_additive]
theorem mem_zpowers_zpow_iff {g : G} {k : ℤ} :
    g ∈ Subgroup.zpowers (g ^ k) ↔ k.gcd (orderOf g) = 1 := by sorry
```
The original lemma was formulated in a very specific setting for the need of the finiteness proof: stating that an element of order zero does not lie in the subgroup generated by its square. It is sufficient for the local use but too specilized from the perspective of library, because it fixed the exponent to $2$ and directly encoded the intended contradiction in the statement itself.

The first generalization relaxed this rigidity by abstracting over the exponent: the statement was extended to $g^k$ for any natural number $k > 1$. Though this modification removed an arbitrary constant and made the result applicable in a broader range of situations, it doesn't change the conceptual level of the lemma. That means, one specific instance $g^2$ is lifted into a family of cases for $g^k$, but it still talks about that the finite cyclic group cannot contain an infinite element. While this is a useful observation, it remains somewhat isolated and does not yet reveal deeper structural information.

The second generalization goes much further, it reformulates the statement as a structural characterization: $g in $ Subgroup.zpowers($g^k$) $arrow.l.r.long$ gcd(k, orderOf(g)) = 1.The lemma is no longer tied to the original finiteness argument; it becomes a standalone structural fact about cyclic subgroups and divisibility properties. At this stage, the abstraction level has shifted from a problem-driven auxiliary statement to a library-oriented characterization theorem. This progression illustrates how review suggestions aim not merely at increasing generality, but at uncovering the structural principle behind a lemma and expressing it at an appropriate level of abstraction for long-term reuse. 

