#import "../template.typ": *

= Formalization of a Theorem on Abelian Simple Groups
This section documents the formalization of a theorem on abelian simple groups. A substantial part of this development has been incorporated into mathlib through an accepted pull request@luo_pr. To illustrate the formalization process, I refer to the initial version of the development rather than the final merged code, as it more clearly reflects the design decisions and intermediate steps discussed in Section 3.2. However, the main idea of this section is not to explain the formalization in detail, but to show how this formal proof structurally aligns with the paper proof. The section 3.4 about mathlib pull request is not a part which stands alone from the formalization of abelian simple group, but as continuation and refinement.

== Mathematical Statement
#theorem[abelian simple groups][Let $G$ be an abelian simple group. Then $G tilde.equiv ZZ_p$ for some prime $p$.]
No finiteness assumption for $G$ is required. 

The rough proof idea for this theorem is as follows: every subgroup of an abelian group is normal. The normal subgroups of a simple group if itself and the trivial subgroup. Let $g in G$ be an non-identity element. The subgroup generated by $g$ must therefore coincide with $G$, so $G$ is cyclic. A cyclic simple group must have prime order, since every cyclic group of order $n$ has a subgroup of order $d$ for each divisor $d | n$(according to Lagrange’s theorem), a cyclic group with composite order admits a nontrivial proper subgroup. Hence, simplicity forces the order of $G$ to be prime. Since $G$ is cyclic of prime order $p$, it is isomorphic to the cyclic group $ZZ_p$. This yields the conclusion.
== API Landscape

Before formalizing the theorem in Lean, it is necessary to determine an appropriate formal statement by researching the relevant group theoretic API.

Firstly, I consider how to do the correct theorem statement. In mathlib, abelian groups are represented by typeclass `[CommGroup G]`, and simplicity is expressed as `[IsSimpleGroup G]`. The trivial subgroup in Lean is expressed as `⊥`, while a group itself is expressed as `⊤`. 

Expressing the statement in Lean requires more care than in the classical paper-and-pencil setting. On paper, one simply write $G tilde.equiv H$ without specifying whether the group is considered additively or multiplicatively. In contrast, mathlib distinguishes explicitly between multiplicative and additive algebraic structures, as these correspond to different typeclasses and operations. To avoid duplicating lemmas for both versions, mathlib primarily develops group theory in the multiplicative setting. Additive analogues are typically generated using the `[to_additive]` attribute. Consequently, when stating the theorem formally, one must explicitly decide whether to work in the multiplicative or additive version. In our development, given that $ZZ_p$ is an additive group, I need an additive isomorphism as well. So the `Additive` wrapper must be applied to the multipilicative group `G`.

Additionally, I always need to consider type correctness when working in a dependent-type based proof assistant. In Lean, a theorem must be of type `Prop`. Because `(Additive G ≃+ ZMod p)` is not of type `Prop` but a data-carrying type of additive equivalence, I cannot directly write it down as a theorem. Here I need the help of `Nonempty`, which is a Prop-valued type class asserting that the type `α` is inhabited. It helps to fit the isomorphism into the existential statement.

Secondly, I investigate whether there are existing tools in the library. I notice that there's already a lemma expressing the isomorphism from $ZZ_n$ to any cyclic additive group which has cardinality `n`. That solves the second half of the proof. Then I find that there's another theorem in API expressing that a finite abelian simple group has prime cardinality. Since an abelian simple group must be cyclic, if I could derive finiteness only from the premises of a group is abelian and simple, then I could formalize theorem 3.1.1 in Lean and generalize the lemma in mathlib as well. Therefore, the main difficulty of this formalization reduces to deriving finiteness from the assumptions of commutativity and simplicity.

== Formalization
The theorem 3.1.1 is thus expressed in Lean as:
```lean
/-- A commutative simple group is isomorphic to `ZMod p` from some prime `p`. -/
theorem CommSimple_iso_ZMod_p [CommGroup G] [IsSimpleGroup G] :
    ∃ p : ℕ , (Nat.Prime p) ∧ Nonempty (Additive G ≃+ ZMod p) := by
  obtain ⟨g, hg⟩ := isCyclic_iff_exists_zpowers_eq_top.mp (inferInstance : IsCyclic G)
  use orderOf g; rw [← (orderOf_eq_card_of_zpowers_eq_top hg).symm]
  constructor
  · exact IsSimpleGroup.prime_card
  · exact ⟨(zmodAddCyclicAddEquiv (G := Additive G) inferInstance).symm⟩
```
Thanks to the typeclass design, I could directly get a cyclic group `hg` and its generator `g` by instance inference. They are being used as the working horse in this proof, because I want to show that `hg` is a finite cyclic group and the order of`g` must be a prime number. The tactic `constructor` splits the AND-connector, divides the theorem into two goals. In the second goal I use the lemma `zmodAddCyclicAddEquiv` from the API and solve the isomorphism for free. In the first goal, the lemma `IsSimpleGroup.prime_card` requires a `Finite α` instance. Since no such instance is available by typeclass inference, I prove finiteness of any abelian simple group separately:
```lean
/-- A commutative simple group is a finite group. -/
theorem comm_simple_is_finite : Finite α := by sorry
```
As mentioned above, I need to construct a proof term which has type `Finite α`.   Similarly, I would like to get a cyclic group by typeclass inference because of the nice mathematical properties and rich API of cyclic groups. The proof idea is be that a subgroup of an infinite cyclic group is neither itself nor trivial subgroup, then the proof is be done by contradiction.

The formal proof skeleton is sketched as follows：
```lean
theorem comm_simple_is_finite : Finite α := by
  obtain ⟨g, hg⟩ :=
    (isCyclic_iff_exists_zpowers_eq_top : IsCyclic α  ↔ _).mp 
    (by infer_instance)
  by_contra hnf
  have horder : orderOf g = 0 := by sorry
  let H : Subgroup α  := Subgroup.zpowers (g ^ 2)
  have Hnorm : H.Normal := by exact Subgroup.normal_of_comm H
  have hneq_top : H ≠ ⊤ := by sorry
  have hneq_bot : H ≠ ⊥ := by sorry
  have := IsSimpleGroup.eq_bot_or_eq_top_of_normal (H := H) Hnorm
  rcases this <;> contradiction
``` 

I firstly obtain a generator `g` using typelcass inference. 
```lean
  obtain ⟨g, hg⟩ :=
    (isCyclic_iff_exists_zpowers_eq_top : IsCyclic α  ↔ _).mp 
    (by infer_instance)
```
This gives a cyclic structure on `α`, with `g` generating the whole group.
To construct a term of type `Finite α`, we proceed by concradiction:
```lean 
  by_contra hnf
```
In mathlib, the order of an element with infinite order is defined as zero. Now assuming the infiniteness, I derive that the order of the generator is zero: ```lean 
  have horder : orderOf g = 0 := by sorry
```
Then I define the subgroup generated by $g^2$:
```lean
  let H : Subgroup α := Subgroup.zpowers (g ^ 2)

```
Since the group is commutative, every subgroup is normal, which allows us to apply the simplicity condition: 
```lean
  have Hnorm : H.Normal := by exact Subgroup.normal_of_comm H
```
It remains to show that `H` is neither trivial nor the whole group. This contradicts the fact that a simple group admits only `⊥` and `⊤` as normal subgroups, completing the proof. The structure of the proof mirrors the mathematical argument, but the explicit construction of subgroups and normality witnesses makes the contradiction step fully transparent in the formal setting.

In the formalization of abelian simple groups, several aspects require explicit attention. These points do not change the underlying mathematical strategy, but illustrate how implicit reasoning in paper proofs becomes explicit in the formal setting:
- *Typeclass inference and reuse*: the proof relies heavily on Lean’s typeclass mechanism, which enables structural properties to propagate automatically throughout the development. Cyclicity is obtained via instance inference, allowing us to extract a generator without explicit construction. Likewise, normality in the abelian setting is available as an instance and can be invoked directly. This mechanism significantly reduces boilerplate and makes existing API results immediately reusable.
- *Explicit structural witnesses*:
  several steps that are immediate in the informal proof require explicit witnesses in formal proof. For instance, although every subgroup of an abelian group is normal, a term of normal subgroup  must be showed in order to feed it into related lemmas. Similarly, the subgroup $⟨g²⟩$ must be shown explicitly to be nontrivial and distinct from the whole group, corresponding to separate proof goals.
- *Type correctness*: while informal proofs rarely make type considerations explicit, in Lean type correctness is a foundational requirement, and every statement must be formulated with precise attention to the types involved.

Although the formal development may appear more technical, the overall structure of the proof remains very close to the classical pen-and-paper proof. This is mainly due to the well-designed group theory API, where concepts like cyclic groups, normal subgroups, cardinality, and simplicity are already abstracted in a way that mirrors standard mathematical practice. As a result, the formal proof does not require a fundamentally different strategy, but reveals implicities in informal math proofs into explicit terms, such as normality witnesses, typeclass instances, and data-carrying equivalences. The differences therefore lie not in the mathematical content, but in the explicit management of structure required by the dependent type theory underlying Lean.

== Mathlib Pull Request

Code written for a local development often prioritizes convenience or for its own project use, while library code must prioritize generality and composability and align with its design philosophy. When preparing the PR, we usually need to do the following: change the naming convention to match the mathlib style, make the proof more compact, break large proofs into several smaller lemmas. What is also important, is to determine the PR scope and the right location to place the contribution by thoroughly studying the related mathlib section, because it is required clearly in the contribution guidelines that contributors are expected to give in this information in their PR message@mathlib_contribute. 

The target theorem with unnecessary `[Finite G]` premise is `IsSimpleGroup.prime_card` which is in the file `Mathlib.GroupTheory.SpecificGroup.Cyclic`. My PR is aimed to remove this premise by adding the proof of finiteness. After researching the file, I notice that the isomorphism theorem is also not included in mathlib. Considering it serves a very classical and fundamental result in undergraduate abstract algebra, I also decide to include this isomorphism lemma in our PR. The file `Cyclic` is arranged by different namespaces with different conditions. I find that the right place to put my lemma should be namespace `IsSimpleGroup`, where I rename the section `CommGroup` into `CommSimpleGroup` to better serve the assumptions. And the right place for the isomorphism lemma is in section `Zmod`. 

Moreover, I refactor the finiteness proof by adding a lemma which I think might be useful in other proofs since it serves as a standard fact. In my proof this lemma  is used in the proof where <$g^2$>$eq.not ⊥ $.  
```lean
lemma not_mem_zpowers_sq_of_orderOf_zero {g : α} (horder : orderOf g = 0) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry
```
Since it doesn't talks about abelian simple groups anymore, rather focusing on the order of elements from a group, we put this lemma in the file `Mathlib.GroupTheory.OrderOfElement`. I decide to pack this lemma together in one PR, because it is derived directly from the proof of finiteness and stay close with the main idea of this PR. After pushing the pull request, the PR is labeled as `t-group-theory`. Since this is my first PR, `new contributor` is also added.

Given that mathlib is a community-driven project, the communication with the mathlib maintainers/viewers and the broad mathlib community is also crucial. After having done all the preparation, I introduce my motivation and this PR in mathlib channel. This action get positive feedback -  mathlib maintainer gives me the first view very soon, even if there are still lots of PRs in the long waitlist.

The feedback received during the review process can be categorized into the following aspects: 
- *Formatting*: several remarks pointed out inconsistencies in indentation, the use of blank lines, and spacing. Although these issues do not affect correctness, they are essential for readability and for maintaining stylistic consistency within a large collaborative project such as mathlib. Before submitting the pull request, I have already reviewed the code according to these conventions; however, the feedback reveals that I overlooked certain details. This experience underscores how subtle and demanding stylistic consistency can be in practice.
- *Naming conventions and comments*: theorems in mathlib also have naming conventions. It must be simplistic and as self explanatory as possible. However for a newcomer it is often confusing to guess what kind of name a theorem should have. This on the other side is a very crucial skill because a better name guessing is meanwhile more efficient navigating in mathlib documentation and theorem finding. My summarization for naming is that it tends to be a compact theorem statement which contains the information in the context than just stating the facts, there's some subtle differences in it: for example, name of theorem `comm_simple_is_finite` is suggested to change into `IsSimpleGroup.finite`, because it is in the namespace of `IsSimpleGroup`, and `comm` and `simple` already serve as premises. Another example is the isomorphism theorem `CommSimple_iso_ZMod_p` is suggested as `exists_prime_addEquiv_ZMod`, since it expresses the existential fact of a prime number and the isomorphism is an additive equivalence. 
- *Code style*: tactic usage is more compact in mathlib. If a term could directly close the goal, then there's no need to use `by refine...`. Expressions should be written in their most direct form, such as writing `(…).symm` instead of `Eq.symm (…)`.
- *Design decisions and library integration*: an interesting discussion arises during the viewing process is whether the finiteness proof should be an instance/scoped instance or just a theorem, as `Finite α` is a type class, term of this type should be registered as an instance if it was possible. After trying to register it as an instance, I have noticed that it makes the performance of the automation tool `aesop` @aesop degenerate, and has caused a proof cannot compile anymore in a number theory file in mathlib. This is because `Finite α` is a fundamental typeclass which supports many other typeclasses. The search of automation tool is rather brute force. Whenever a finiteness proof is needed, the instance search will be triggered. As a newly added instance with relatively narrow usage, `IsSimple.finite` has higher priority, which causes `aesop` stuck in the reasoning, leading to a time out. After discussing with the community, `scoped instance` is also not preferred because finiteness is not something that people want to automatically get from when mentioning "abelian" and "simple". In the end, this proof is finally registered as a theorem in mathlib.
- *Lemma generalization and abstraction level*: The most intensive part of the review process is when the reviewer suggests generalizing a lemma. On the one hand it provides a valuable opportunity to learn how experienced contributors think about abstraction and how a lemma can better serve the library in the long term. On the other hand, such suggestions often require additional work, and the connection between the proposed generalization and the original direction of the PR is not always immediately clear. This intermediate lemma for the proof of finiteness has been asked for generalization two times:
```lean
/-The original version-/
@[to_additive]
lemma not_mem_zpowers_sq_of_orderOf_zero {g : α} (horder : orderOf g = 0) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry

/-The first generalization-/
@[to_additive]
theorem not_mem_zpowers {g : α} {k : ℕ} (horder : orderOf g = 0)
    (hk : 1 < k) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry

/-The second generalization-/
@[to_additive]
theorem mem_zpowers_zpow_iff {g : G} {k : ℤ} :
    g ∈ Subgroup.zpowers (g ^ k) ↔ k.gcd (orderOf g) = 1 := by sorry
```
The original lemma is formulated in a very specific setting for the need of the finiteness proof: stating that an element of order zero does not lie in the subgroup generated by its square. It is sufficient for the local use but too specialized from the perspective of library, because it fixes the exponent to $2$ and directly encodes the intended contradiction in the statement itself.

The first generalization relaxes this rigidity by abstracting over the exponent: the statement is extended to $g^k$ for any natural number $k > 1$. Though this modification removes an arbitrary constant and makes the result applicable in a broader range of situations, it doesn't change the conceptual level of the lemma. That means, one specific instance $g^2$ is lifted into a family of cases for $g^k$, but it still talks about that the finite cyclic group cannot contain an infinite element. While this is a useful observation, it remains somewhat isolated and does not yet reveal deeper structural information.

The second generalization goes much further, it reformulates the statement as a structural characterization: $g in $ Subgroup.zpowers($g^k$) $arrow.l.r.long$ gcd(k, orderOf(g)) = 1.The lemma is no longer tied to the original finiteness argument; it becomes a standalone structural fact about cyclic subgroups and divisibility properties. At this stage, the abstraction level shifts from a problem-driven auxiliary statement to a library-oriented characterization theorem. This progression illustrates how review suggestions aim not merely at increasing generality, but at uncovering the structural principle behind a lemma and expressing it at an appropriate level of abstraction for long-term reuse. 

