#import "../template.typ": *

= Formalization of a Theorem on Abelian Simple Groups
This section documents the formalization of a theorem on abelian simple groups. The motivation of this formalization comes from an investigation of the corresponding formalization of an exercise in Dummit&Foote: I notice that the existing theorem in Mathlib assumes some unnecessary premises.  A substantial part of this development has been incorporated into Mathlib through an accepted pull request#footnote[https://github.com/leanprover-community/mathlib4/pull/32152] discussed in @3.3. To illustrate the formalization process, I refer to the initial version of the development rather than the final merged code, as it more clearly reflects the design decisions and intermediate steps discussed in @3.2. The main idea of this section is not to explain the formalization in detail, but to show how this formal proof structurally aligns with the paper proof. 

== Mathematical Statement <3.1>
#theorem[abelian simple groups][Let $G$ be an abelian simple group. Then $G tilde.equiv ZZ_p$ for some prime $p$.]
No finiteness assumption for $G$ is required. 

The rough proof idea for this theorem is as follows: every subgroup of an abelian group is normal. The normal subgroups of a simple group if itself and the trivial subgroup. Let $g in G$ be an non-identity element. The subgroup generated by $g$ must therefore coincide with $G$, so $G$ is cyclic. Now we distinguish $G$ from an infinite case and a finite case:
- An infinite cyclic simple group cannot exist. If it does, then we can choose one of its subgroup which is generated from a single element $g^2$. Since <$g^2$> cannot be the trivial subgroup nor the subgroup itself, this leads to contradiction.
-  A finite cyclic simple group must have prime order, since every cyclic group of order $n$ has a subgroup of order $d$ for each divisor $d | n$ (according to Lagrange’s theorem), a cyclic group with composite order admits a nontrivial proper subgroup. Hence, simplicity forces the order of $G$ to be prime. Since $G$ is cyclic of prime order $p$, it is isomorphic to the cyclic group $ZZ_p$. This yields the conclusion.
== API Landscape <3.2>

Before formalizing the theorem in Lean, it is necessary to determine an appropriate formal theorem statement by researching the relevant group theoretic API. 

Firstly, I consider how to do the correct theorem statement. In Mathlib, abelian groups are represented by type class `[CommGroup G]`, and simplicity is expressed as `[IsSimpleGroup G]`. The trivial subgroup in Lean is expressed as `⊥`, while a group viewed as a subgroup of itself is expressed as `⊤`. 

Expressing the statement in Lean requires more explicities than in the paper-and-paper proof. On paper, one simply write $G tilde.equiv H$ without specifying whether the group is considered additively or multiplicatively. In contrast, Mathlib distinguishes explicitly between multiplicative and additive algebraic structures, as these correspond to different type classes and operations. To avoid duplicating lemmas for both versions, Mathlib primarily develops group theory in the multiplicative setting. Additive analogues of lemmas are typically generated by using the `[to_additive]` attribute. Consequently, when stating the theorem formally, one must explicitly decide whether to work in the multiplicative or additive version. In my development, given that $ZZ_p$ is an additive group, I need an additive isomorphism as well. With the help of the `Additive` annotation, a multipilicative group `G` is transformed into its additive version.

Additionally, I always need to consider type correctness when working in a dependent-type based proof assistant. In Lean, a theorem must be of type `Prop`. However, the statement `(Additive G ≃+ ZMod p)` is not of type `Prop` but a data-carrying type of additive equivalence. I reformulate the statement as `Nonempty (Additive G ≃+ ZMod p)`, where `Nonempty` is a Prop-valued type class asserting that the type `α` is inhabited. 

Secondly, I survey the existing results in Mathlib relevant to this statement. I notice that the library already contains a lemma expressing that any cyclic additive group of cardinality `n` is isomorphic to $ZZ_n$, which provides the structural component needed. Moreover, Mathlib includes a theorem `IsSimpleGroup.prime_card` stating that a finite abelian simple group has prime cardinality. Since every abelian simple group is cyclic, these results together reduce the formalization task to establishing finiteness from the assumptions of commutativity and simplicity alone.

Therefore, the main technical challenge is to derive finiteness from these assumptions, after which the remaining steps follow directly from existing library results.

== Formalization <3.3>
=== Revisiting the Paper Proof
To clarify the structure of the formalization, I first revisit the paper proof in @3.1 and summarize the logical steps as follows:

*abelian simple group $arrow$ cyclic $arrow$ finite $arrow$ prime order $arrow$ $ZZ_p$*.

As discussed in @3.2,  several parts of this logical chain are already available in Mathlib, especially from `finite` to $ZZ_p$. If I also follow the proof idea from  the first half of the logical steps above, then the overall structure of the formal proof can be closely align with the paper proof. The main missing ingredient in the formalization is the derivation of finiteness from the assumptions that the group is abelian and simple, by using cyclicity.
Once this is established, the remaining parts of the argument can be assembled from the existing API with minimal additional work.
#pagebreak()

=== The Formal Proof 
The theorem 3.1.1 is thus expressed in Lean as:
```lean
/-- A commutative simple group is isomorphic to `ZMod p` from some prime `p`. -/
theorem CommSimple_iso_ZMod_p {G : Type*} [CommGroup G] [IsSimpleGroup G] :
    ∃ p : ℕ , (Nat.Prime p) ∧ Nonempty (Additive G ≃+ ZMod p) := by
  obtain ⟨g, hg⟩ := isCyclic_iff_exists_zpowers_eq_top.mp (inferInstance : IsCyclic G)
  use orderOf g; rw [← (orderOf_eq_card_of_zpowers_eq_top hg).symm]
  constructor
  · exact IsSimpleGroup.prime_card
  · exact ⟨(zmodAddCyclicAddEquiv (G := Additive G) inferInstance).symm⟩
```
The goal is to show that the abelian group has order prime `p` and it is isomorphic to `ZZ_p`. 

First, I use the fact that an abelian simple group is cyclic:
```lean
obtain ⟨g, hg⟩ := 
  isCyclic_iff_exists_zpowers_eq_top.mp (inferInstance : IsCyclic G)
```
The reason why such kind of cyclic group exists and one can directly get it from Mathlib by instance inference is that the instance `IsSimpleAddGroup.isAddCyclic` is already registered in Mathlib. This provides a generator $g$ of $G$, together with the information that $G$ $=$ <$g$>. 

I then choose the witness $p$ to be the order of the generator, i.e.$p$ = orderOf($g$). Since the cyclicity proof gives $G$ $=$ <$g$>, Mathlib yields the identity $|G| =$ orderOf($g$), which is done by the lemma `orderOf_eq_card_of_zpowers_eq_top`. Together these steps are expressed as:
```lean
use orderOf g; rw [← (orderOf_eq_card_of_zpowers_eq_top hg).symm]
```
Rewriting the goal using this equality reduces the statement to the fact that the cardinality of $G$ is prime.
At this point I invoke the generalized theorem `IsSimpleGroup.prime_card`, which states that a commutative simple group has prime cardinality.
Finally, the lemma `zmodAddCyclicAddEquiv` provides the desired isomorphism between $G$ and $ZZ_p$.

In order to generalize the lemma `IsSimpleGroup.prime_card`, I need to provide a finiteness proof, by constructing a proof term which has type `Finite α`. Its formal proof follows exactly the first bullet point of paper proof in @3.1. And its proof skeleton is formalized as follows:
```lean
theorem comm_simple_is_finite {α : Type*}
    [CommGroup α] [IsSimpleGroup α]: Finite α := by
  obtain ⟨g, hg⟩ :=
    (isCyclic_iff_exists_zpowers_eq_top : IsCyclic α  ↔ _).mp 
    (by infer_instance)
  by_contra hnf
  have horder : orderOf g = 0 := by sorry -- proof omitted
  let H : Subgroup α  := Subgroup.zpowers (g ^ 2)
  have Hnorm : H.Normal := by exact Subgroup.normal_of_comm H
  have hneq_top : H ≠ ⊤ := by sorry -- proof omitted
  have hneq_bot : H ≠ ⊥ := by sorry -- proof omitted
  have := IsSimpleGroup.eq_bot_or_eq_top_of_normal (H := H) Hnorm
  rcases this <;> contradiction
``` 
Similarly as the main theorem, I firstly obtain a cyclic group `hg` and its generator `g` by using type lcass inference. 
Then I proceed my proof by concradiction, which adds the hypothesis `hnf: ¬Finite α`:
```lean 
  by_contra hnf
```
In Mathlib, the order of an element with infinite order is defined as zero:
```lean 
  have horder : orderOf g = 0 := by sorry
```
In order to show the existence of nontrival normal subgroup, I define a subgroup `H` generated by $g^2$, and show the normalness of `H`:
```lean
  let H : Subgroup α := Subgroup.zpowers (g ^ 2)
  have Hnorm : H.Normal := by exact Subgroup.normal_of_comm H
```
Now it remains to show that `H` is neither trivial (just showing that `H` is not equal to `⊥`) nor the `⊤` (where I need a lemma `not_mem_zpowers_sq_of_orderOf_zero`, which I will talk about in @3.4). This contradicts the fact that a simple group admits only `⊥` and `⊤` as normal subgroups by using the existing lemma, completing the proof:
```lean
have := IsSimpleGroup.eq_bot_or_eq_top_of_normal (H := H) Hnorm
rcases this <;> contradiction
``` 

The structure of the proof mirrors the mathematical argument, but the explicit construction of subgroups and normality witnesses makes the contradiction step fully transparent in the formal setting.

I summarize several points of this formal proof where implicit reasoning in paper proofs becomes explicit:
- *Type class inference and reuse*: the proof relies a lot on Lean's typeclass mechanism, which enables structural properties to propagate automatically throughout the development. Cyclicity is obtained via instance inference, allowing us to extract a generator without explicit construction. Likewise, normality in the abelian setting is available as an instance and can be invoked directly. This mechanism significantly reduces boilerplate and makes existing API results immediately reusable.
- *Explicit structural witnesses*:
  several steps that are immediate in the informal proof require explicit witnesses in formal proof. For instance, although every subgroup of an abelian group is normal, a term of normal subgroup  must be showed in order to feed it into related lemmas. Similarly, the subgroup $⟨g²⟩$ must be shown explicitly to be nontrivial and distinct from the whole group, corresponding to separate proof goals.
- *Type correctness*: while informal proofs rarely make type considerations explicit, in Lean type correctness is a foundational requirement, and every statement must be formulated with precise attention to the types involved.

Although the formal development may appear more technical, the overall structure of the proof remains very close to the classical pen-and-paper proof. This is mainly due to the well-designed group theory API, where concepts like cyclic groups, normal subgroups, cardinality, and simplicity are already abstracted in a way that mirrors standard mathematical practice. As a result, the formal proof does not require a fundamentally different strategy, but reveals implicites in informal math proofs into explicit terms, such as normality witnesses, typeclass instances, and data-carrying equivalences. The differences therefore lie not in the mathematical content, but in the explicit management of structure required by the dependent type theory underlying Lean.

== Mathlib Pull Request<3.4>
=== The Process and Feedback
Code written for a local development often prioritizes convenience or for its own project use, while library code must prioritize generality and composability and align with its design philosophy. When preparing the PR, we usually need to do the following@mathlib_contribute: change the naming convention to match the Mathlib style, make the proof more compact, break large proofs into several smaller lemmas. What is also important, is to determine the PR scope and the right location to place the contribution by thoroughly studying the related Mathlib section, because it is required clearly in the contribution guidelines that contributors are expected to give in this information in their PR message. 

The target theorem with unnecessary `[Finite G]` premise is `IsSimpleGroup.prime_card` which is in the file `Mathlib.GroupTheory.SpecificGroup.Cyclic`. My PR is aimed to remove this premise by adding the proof of finiteness. After researching the file, I notice that the isomorphism theorem is also not included in Mathlib. Considering it serves a very classical and fundamental result in undergraduate abstract algebra, I also decide to include this isomorphism lemma in my PR. The file `Cyclic` is arranged by different namespaces with different conditions. I find that the right place to put my lemma should be namespace `IsSimpleGroup`, where I rename the section `CommGroup` into `CommSimpleGroup` to better serve the assumptions. And the right place for the isomorphism lemma is in section `Zmod`. 

Moreover, I refactor the finiteness proof by adding a lemma which I think might be useful in other proofs since it serves as a standard fact. In my proof this lemma  is used in the proof of theorem `comm_simple_is_finite` where ```lean have hneq_top : H ≠ ⊤``` in @3.3.
```lean
lemma not_mem_zpowers_sq_of_orderOf_zero {g : α} (horder : orderOf g = 0) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry
```
Since it doesn't talk about abelian simple groups anymore, rather focusing on the order of elements from a group, I put this lemma in the file `Mathlib.GroupTheory.OrderOfElement`. Finally I pack this lemma together together in one PR, because it is derived directly from the proof of finiteness and stay close with the main idea of this PR. After pushing the pull request, the PR is labeled as `t-group-theory`. Since this is my first PR, `new contributor` is also added.

The communication with the Mathlib maintainers/viewers and the broad Mathlib community is also crucial. After having done all the preparation, I introduce my motivation and this PR in Mathlib channel on Zulip and get positive feedback: Mathlib maintainer gives me the first view very soon, even if there are still lots of PRs in the long waitlist.

The feedback can be categorized into the following aspects: 
- *Formatting*: several remarks pointed out inconsistencies in indentation, the use of blank lines, and spacing. Although these issues do not affect correctness, they are essential for readability and for maintaining stylistic consistency within a large collaborative project such as Mathlib. Before submitting the pull request, I have already reviewed the code according to these conventions; however, the feedback reveals that I overlooked certain details. This experience underscores how subtle and demanding stylistic consistency can be in practice.
- *Naming conventions and comments*: theorems in Mathlib have naming conventions. It must be simplistic and as self explanatory as possible. However for a newcomer it is often confusing to guess what kind of name a theorem should have. This is a very crucial skill because a better name guessing means more efficient navigating in Mathlib documentation and theorem finding. My summarization for naming is that it tends to be a compact theorem statement which contains the information in the context than just stating the facts, there's some subtle differences in it: for example, name of theorem `comm_simple_is_finite` is suggested to change into `IsSimpleGroup.finite`, because it is in the namespace of `IsSimpleGroup`, and `comm` and `simple` already serve as premises. Another example is the isomorphism theorem `CommSimple_iso_ZMod_p` is suggested as `exists_prime_addEquiv_ZMod`, since it expresses the existential fact of a prime number and the isomorphism is an additive equivalence. 
- *Code style*: tactic usage is more compact in Mathlib. If a term could directly close the goal, then there's no need to use `by refine...`. Expressions should be written in their most direct form, such as writing `(…).symm` instead of `Eq.symm (…)`.
- *Design decisions and library integration*: an interesting discussion arises during the viewing process is whether the finiteness proof should be an instance/scoped instance or just a theorem, as `Finite α` is a type class, term of this type should be registered as an instance if it was possible. After trying to register it as an instance, I have noticed that it makes the performance of the automation tool `aesop` @aesop degenerate, and has caused a proof cannot compile anymore in a number theory file in Mathlib. This is because `Finite α` is a fundamental typeclass which supports many other typeclasses. The search of automation tool is rather brute force. Whenever a finiteness proof is needed, the instance search will be triggered. As a newly added instance with relatively narrow usage, `IsSimple.finite` has higher priority, which causes `aesop` stuck in the reasoning, leading to a time out. After discussing with the community, `scoped instance` is also not preferred because finiteness is not something that people want to automatically get from when mentioning "abelian" and "simple". In the end, this proof is finally registered as a theorem in Mathlib.

=== Lemma Generalization
The most intensive part of the review process is when the reviewer suggests generalizing a lemma. On the one hand it provides a valuable opportunity to learn how experienced contributors think about abstraction and how a lemma can better serve the library in the long term. On the other hand, such suggestions often require additional work, and the connection between the proposed generalization and the original direction of the PR is not always immediately clear. This intermediate lemma for the proof of finiteness has been asked for generalization two times:
```lean
/-The original version-/
@[to_additive]
lemma not_mem_zpowers_sq_of_orderOf_zero {g : α} (horder : orderOf g = 0) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry

/-The first generalization-/
@[to_additive]
theorem not_mem_zpowers {g : α} {k : ℕ} (horder : orderOf g = 0)
    (hk : 1 < k) :
    g ∉ (Subgroup.zpowers (g ^ 2)) := by sorry

/-The second generalization-/
@[to_additive]
theorem mem_zpowers_zpow_iff {g : G} {k : ℤ} :
    g ∈ Subgroup.zpowers (g ^ k) ↔ k.gcd (orderOf g) = 1 := by sorry
```
- The original lemma is formulated in a very specific setting for the need of the finiteness proof: stating that an element of order zero does not lie in the subgroup generated by its square. It is sufficient for the local use but too specialized from the perspective of library, because it fixes the exponent to $2$ and directly encodes the intended contradiction in the statement itself.

- The first generalization relaxes this rigidity by abstracting over the exponent: the statement is extended to $g^k$ for any natural number $k > 1$. Though this modification removes an arbitrary constant and makes the result applicable in a broader range of situations, it doesn't change the conceptual level of the lemma. That means, one specific instance $g^2$ is lifted into a family of cases for $g^k$, but it still talks about that the finite cyclic group cannot contain an infinite element. While this is a useful observation, it remains somewhat isolated and does not yet reveal deeper structural information.

- The second generalization goes much further, it reformulates the statement as a structural characterization: $g in $ Subgroup.zpowers($g^k$) $arrow.l.r.long$ gcd(k, orderOf(g)) = 1.The lemma is no longer tied to the original finiteness argument; it becomes a standalone structural fact about cyclic subgroups and divisibility properties. At this stage, the abstraction level shifts from a problem-driven auxiliary statement to a library-oriented characterization theorem. 






